use_frameworks!
platform :ios, '9.0'


def shared_pod
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'Reachability'
    pod 'PINCache'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'JPush', '3.1.0'
    pod 'MJExtension', '~> 3.0.13'
end

target 'proList' do
    
    shared_pod
    
end
